#Author: your.email@your.domain.com
#Keywords Summary :
#Feature: List of scenarios.
#Scenario: Business rule through list of steps with arguments.
#Given: Some precondition step
#When: Some key actions
#Then: To observe outcomes or validation
#And,But: To enumerate more Given,When,Then steps
#Scenario Outline: List of steps for data-driven as an Examples and <placeholder>
#Examples: Container for s table
#Background: List of steps run before each of the scenarios
#""" (Doc Strings)
#| (Data Tables)
#@ (Tags/Labels):To group Scenarios
#<> (placeholder)
#""
## (Comments)
#Sample Feature Definition Template
@tag
Feature: Token generator
 generate tokens for customer

  @tag1
  Scenario: Request Token
  
	Given a registered customer
	Given the customer has no more than one valid token
	When the customer requests 5 tokens from the token service
	Then 5 tokens are generated by the token service
	And the token service assigns 5 tokens to the registered customer
	
  @tag2
  Scenario: Request Token Denied
  
 	Given a registered customer with a bank account 	
	Given the customer has more than one valid token 
	When the customer requests 5 tokens from the token service
	Then the request is denied